// ============================================
// WEAPON DATA CONFIGURATION
// All weapon definitions in a single JSON-like structure
// Easy to extend and balance
// ============================================

const WEAPON_DATA = {
  // Pistols
  pistol: {
    id: 'pistol',
    name: 'M9 Pistol',
    category: 'pistol',
    type: 'hitscan',
    damage: 25,
    fireRate: 0.15,
    magazineSize: 12,
    maxAmmo: 120,
    reloadTime: 1.5,
    spread: 0.02,
    spreadIncrease: 0.005,
    spreadRecovery: 0.1,
    recoil: { x: 0.02, y: 0.03, z: 0 },
    recoilRecovery: 8,
    range: 100,
    fireMode: 'semi',
    burstCount: 0,
    burstDelay: 0,
    adsFOV: 55,
    adsSpeed: 0.2,
    muzzleFlashDuration: 0.05,
    shellEjection: true,
    sounds: {
      fire: '/sounds/pistol_fire.mp3',
      empty: '/sounds/pistol_empty.mp3',
      reload: '/sounds/pistol_reload.mp3',
      ads: '/sounds/ads.mp3',
      dry: '/sounds/dry_fire.mp3',
    },
    stats: {
      accuracy: 85,
      handling: 90,
      range: 60,
      damage: 45,
    },
  },
  
  // Assault Rifles
  rifle: {
    id: 'rifle',
    name: 'AR-15 Assault Rifle',
    category: 'rifle',
    type: 'hitscan',
    damage: 18,
    fireRate: 0.08,
    magazineSize: 30,
    maxAmmo: 240,
    reloadTime: 2.0,
    spread: 0.035,
    spreadIncrease: 0.008,
    spreadRecovery: 0.15,
    recoil: { x: 0.025, y: 0.04, z: 0 },
    recoilRecovery: 6,
    range: 150,
    fireMode: 'auto',
    burstCount: 0,
    burstDelay: 0,
    adsFOV: 45,
    adsSpeed: 0.25,
    muzzleFlashDuration: 0.05,
    shellEjection: true,
    sounds: {
      fire: '/sounds/rifle_fire.mp3',
      empty: '/sounds/rifle_empty.mp3',
      reload: '/sounds/rifle_reload.mp3',
      ads: '/sounds/ads.mp3',
      dry: '/sounds/dry_fire.mp3',
    },
    stats: {
      accuracy: 75,
      handling: 70,
      range: 80,
      damage: 55,
    },
  },
  
  // SMG
  smg: {
    id: 'smg',
    name: 'MP5 Submachine Gun',
    category: 'smg',
    type: 'hitscan',
    damage: 14,
    fireRate: 0.05,
    magazineSize: 40,
    maxAmmo: 320,
    reloadTime: 1.8,
    spread: 0.05,
    spreadIncrease: 0.012,
    spreadRecovery: 0.2,
    recoil: { x: 0.03, y: 0.025, z: 0 },
    recoilRecovery: 7,
    range: 60,
    fireMode: 'auto',
    burstCount: 0,
    burstDelay: 0,
    adsFOV: 50,
    adsSpeed: 0.15,
    muzzleFlashDuration: 0.04,
    shellEjection: true,
    sounds: {
      fire: '/sounds/smg_fire.mp3',
      empty: '/sounds/smg_empty.mp3',
      reload: '/sounds/smg_reload.mp3',
      ads: '/sounds/ads.mp3',
      dry: '/sounds/dry_fire.mp3',
    },
    stats: {
      accuracy: 60,
      handling: 95,
      range: 40,
      damage: 35,
    },
  },
  
  // Shotgun
  shotgun: {
    id: 'shotgun',
    name: 'Pump Shotgun',
    category: 'shotgun',
    type: 'hitscan',
    damage: 12,
    pellets: 8,
    fireRate: 0.8,
    magazineSize: 6,
    maxAmmo: 48,
    reloadTime: 2.5,
    spread: 0.15,
    spreadIncrease: 0.02,
    spreadRecovery: 0.08,
    recoil: { x: 0.05, y: 0.08, z: 0 },
    recoilRecovery: 4,
    range: 40,
    fireMode: 'semi',
    burstCount: 0,
    burstDelay: 0,
    adsFOV: 60,
    adsSpeed: 0.3,
    muzzleFlashDuration: 0.08,
    shellEjection: true,
    sounds: {
      fire: '/sounds/shotgun_fire.mp3',
      empty: '/sounds/shotgun_empty.mp3',
      reload: '/sounds/shotgun_reload.mp3',
      ads: '/sounds/ads.mp3',
      dry: '/sounds/dry_fire.mp3',
    },
    stats: {
      accuracy: 40,
      handling: 50,
      range: 20,
      damage: 90,
    },
  },
  
  // Sniper Rifle
  sniper: {
    id: 'sniper',
    name: 'AWP Sniper Rifle',
    category: 'sniper',
    type: 'hitscan',
    damage: 100,
    fireRate: 1.5,
    magazineSize: 5,
    maxAmmo: 40,
    reloadTime: 3.0,
    spread: 0.001,
    spreadIncrease: 0.002,
    spreadRecovery: 0.05,
    recoil: { x: 0.01, y: 0.15, z: 0 },
    recoilRecovery: 3,
    range: 300,
    fireMode: 'semi',
    burstCount: 0,
    burstDelay: 0,
    adsFOV: 20,
    adsSpeed: 0.4,
    muzzleFlashDuration: 0.1,
    shellEjection: true,
    sounds: {
      fire: '/sounds/sniper_fire.mp3',
      empty: '/sounds/sniper_empty.mp3',
      reload: '/sounds/sniper_reload.mp3',
      ads: '/sounds/ads.mp3',
      dry: '/sounds/dry_fire.mp3',
    },
    stats: {
      accuracy: 100,
      handling: 30,
      range: 100,
      damage: 100,
    },
  },
  
  // Burst Rifle
  burstRifle: {
    id: 'burstRifle',
    name: 'Burst Assault Rifle',
    category: 'rifle',
    type: 'hitscan',
    damage: 20,
    fireRate: 0.1,
    magazineSize: 30,
    maxAmmo: 210,
    reloadTime: 2.2,
    spread: 0.03,
    spreadIncrease: 0.006,
    spreadRecovery: 0.12,
    recoil: { x: 0.022, y: 0.035, z: 0 },
    recoilRecovery: 7,
    range: 140,
    fireMode: 'burst',
    burstCount: 3,
    burstDelay: 0.08,
    adsFOV: 48,
    adsSpeed: 0.22,
    muzzleFlashDuration: 0.05,
    shellEjection: true,
    sounds: {
      fire: '/sounds/burst_fire.mp3',
      empty: '/sounds/burst_empty.mp3',
      reload: '/sounds/burst_reload.mp3',
      ads: '/sounds/ads.mp3',
      dry: '/sounds/dry_fire.mp3',
    },
    stats: {
      accuracy: 80,
      handling: 75,
      range: 75,
      damage: 60,
    },
  },
  
  // Grenade Launcher
  launcher: {
    id: 'launcher',
    name: 'M32 Grenade Launcher',
    category: 'heavy',
    type: 'projectile',
    damage: 100,
    explosionRadius: 8,
    fireRate: 1.0,
    magazineSize: 4,
    maxAmmo: 20,
    reloadTime: 3.0,
    spread: 0.01,
    spreadIncrease: 0.005,
    spreadRecovery: 0.1,
    recoil: { x: 0.08, y: 0.12, z: 0 },
    recoilRecovery: 2,
    range: 80,
    projectileSpeed: 40,
    projectileGravity: 15,
    fireMode: 'semi',
    burstCount: 0,
    burstDelay: 0,
    adsFOV: 55,
    adsSpeed: 0.35,
    muzzleFlashDuration: 0.1,
    shellEjection: false,
    sounds: {
      fire: '/sounds/launcher_fire.mp3',
      empty: '/sounds/launcher_empty.mp3',
      reload: '/sounds/launcher_reload.mp3',
      ads: '/sounds/ads.mp3',
      dry: '/sounds/dry_fire.mp3',
    },
    stats: {
      accuracy: 70,
      handling: 40,
      range: 65,
      damage: 95,
    },
  },
  
  // Rocket Launcher
  rocketLauncher: {
    id: 'rocketLauncher',
    name: 'RPG-7',
    category: 'heavy',
    type: 'projectile',
    damage: 150,
    explosionRadius: 12,
    fireRate: 2.0,
    magazineSize: 1,
    maxAmmo: 8,
    reloadTime: 4.0,
    spread: 0.005,
    spreadIncrease: 0.002,
    spreadRecovery: 0.05,
    recoil: { x: 0.1, y: 0.15, z: 0 },
    recoilRecovery: 1.5,
    range: 150,
    projectileSpeed: 60,
    projectileGravity: 8,
    fireMode: 'semi',
    burstCount: 0,
    burstDelay: 0,
    adsFOV: 40,
    adsSpeed: 0.5,
    muzzleFlashDuration: 0.15,
    shellEjection: false,
    sounds: {
      fire: '/sounds/rocket_fire.mp3',
      empty: '/sounds/rocket_empty.mp3',
      reload: '/sounds/rocket_reload.mp3',
      ads: '/sounds/ads.mp3',
      dry: '/sounds/dry_fire.mp3',
    },
    stats: {
      accuracy: 65,
      handling: 20,
      range: 85,
      damage: 100,
    },
  },
};

// Weapon categories for filtering
const WEAPON_CATEGORIES = {
  pistol: { name: 'Pistols', icon: '🔫' },
  rifle: { name: 'Assault Rifles', icon: '🎯' },
  smg: { name: 'SMGs', icon: '⚡' },
  shotgun: { name: 'Shotguns', icon: '💥' },
  sniper: { name: 'Sniper Rifles', icon: '👁️' },
  heavy: { name: 'Heavy Weapons', icon: '🚀' },
};

// Fire modes
const FIRE_MODES = {
  semi: { name: 'Semi-Auto', description: 'One shot per trigger pull' },
  auto: { name: 'Full-Auto', description: 'Continuous fire while holding trigger' },
  burst: { name: 'Burst', description: 'Fixed number of shots per trigger pull' },
};

export { WEAPON_DATA, WEAPON_CATEGORIES, FIRE_MODES };
